cc = g++ 
cflags = -g -std=c++11

files = BinarySearchTree

all: $(files)

BinarySearchTree: BinarySearchTree.cpp
	$(cc) $(cflags) -o BinarySearchTree BinarySearchTree.cpp

clean:
	rm -rf *.out *~ *.o BinarySearchTree

